.TH BSYMLINK "1" "2021" "NNB" "User Commands"
.SH NAME
Bsymlink \- Batch symlink tool that SuperB
.SH SYNOPSIS
.B bsymlink path/to/directory path/to/target [path/to/trash]
.SH DESCRIPTION
Bsymlink is a SuperB batch symlink tool written in exactly 64 lines of pure sh. But unlike Stow, it can move conflict files to the trash.
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/bsymlink/issues
