.TH BSYMLINK "1" "2021" "NNB" "User Commands"
.SH NAME
Bsymlink \- Batch symlink tool that SuperB
.SH SYNOPSIS
.B bsymlink path/to/directory path/to/target [path/to/trash]
.SH DESCRIPTION
Bsymlink is a SuperB batch symlink tool. But unlike Stow, it can handle conflict files like move it to the trash or delete it.
.SH ENVIRONMENT VARIABLES
\fBBSYMLINK_HANDLE\fR
Set the command to handle conflict files.
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/bsymlink/issues
